In [3]:
import numpy as np


def euclidean_distance(point1, point2):
    # Kiểm tra số chiều của hai điểm
    assert len(point1) == len(point2), "Số chiều của hai điểm phải bằng nhau."

    # Tính khoảng cách Euclide
    distance = np.sqrt(np.sum((point2 - point1)**2))
    return distance


# Ví dụ: Tính khoảng cách Euclide giữa hai điểm trong không gian ba chiều
point1 = np.array([8, 4, 200])
point2 = np.array([8, 6, 350])
point3 = np.array([11.29, 6, 388.57])

arr = np.array([[8, 4, 200], [8, 6, 350], [9, 7, 650], [10, 5, 400], [
    11, 4, 320], [11, 8, 250], [12, 6, 600], [12, 7, 300] ,[14, 5, 200],[11,6,450]])
for i in arr:
    print(i)
    distance = euclidean_distance(i, point3)
    distance = "{:.2f}".format(distance) 
    print("Khoảng cách Euclide:", distance)


[  8   4 200]
Khoảng cách Euclide: 188.61
[  8   6 350]
Khoảng cách Euclide: 38.71
[  9   7 650]
Khoảng cách Euclide: 261.44
[ 10   5 400]
Khoảng cách Euclide: 11.55
[ 11   4 320]
Khoảng cách Euclide: 68.60
[ 11   8 250]
Khoảng cách Euclide: 138.58
[ 12   6 600]
Khoảng cách Euclide: 211.43
[ 12   7 300]
Khoảng cách Euclide: 88.58
[ 14   5 200]
Khoảng cách Euclide: 188.59
[ 11   6 450]
Khoảng cách Euclide: 61.43


In [84]:
def average_of_matrices(matrix1, matrix2, matrix3, matrix4):
    # Kiểm tra kích thước của các ma trận
    # assert matrix1.shape == matrix2.shape == matrix3.shape, "Các ma trận phải có cùng kích thước."

    # Cộng các ma trận lại và tính giá trị trung bình
    sum_matrix = matrix1 + matrix2 + matrix3 + matrix4
    average_matrix = sum_matrix / 2
    if(matrix3):
        average_matrix = sum_matrix / 3
    if(matrix4): 
        average_matrix = sum_matrix / 4
    # average_matrix= "{:.2f}".format(distance) 

    return average_matrix 

SyntaxError: invalid syntax (3877248627.py, line 1)

In [70]:
# Tính giá trị trung bình của ba ma trận
print(arr[8])
average_matrix = average_of_matrices(arr[0], arr[5] , arr[8])
average_matrix2 = average_of_matrices(arr[1], arr[4] , arr[7])
average_matrix3 = average_of_matrices(arr[2], arr[3] , arr[6])
print("Ma trận trung bình:")
print(average_matrix)
print("Ma trận trung bình:")
print(average_matrix2)
print("Ma trận trung bình:")
print(average_matrix3)

[ 14   5 200]
Ma trận trung bình:
[ 11.           5.66666667 216.66666667]
Ma trận trung bình:
[ 10.33333333   5.66666667 323.33333333]
Ma trận trung bình:
[ 10.33333333   6.         550.        ]


In [76]:
# Ví dụ: Tính khoảng cách Euclide giữa hai điểm trong không gian ba chiều
point1 = np.array([11, 5.67, 216.67])
point2 = np.array([10.33333333,   5.66666667, 323.33333333])
point3 = np.array([10.33333333,  6.,  550.])

arr = np.array([[8, 4, 200], [8, 6, 350], [9, 7, 650], [10, 5, 400], [
    11, 4, 320], [11, 8, 250], [12, 6, 600], [12, 7, 300], [14, 5, 200]])
for i in arr:
    print(i)
    
    distance = euclidean_distance(i, point1)
    distance = "{:.2f}".format(distance)
    print("Khoảng cách Euclide:", distance)


[  8   4 200]
Khoảng cách Euclide: 17.02
[  8   6 350]
Khoảng cách Euclide: 133.36
[  9   7 650]
Khoảng cách Euclide: 433.34
[ 10   5 400]
Khoảng cách Euclide: 183.33
[ 11   4 320]
Khoảng cách Euclide: 103.34
[ 11   8 250]
Khoảng cách Euclide: 33.41
[ 12   6 600]
Khoảng cách Euclide: 383.33
[ 12   7 300]
Khoảng cách Euclide: 83.35
[ 14   5 200]
Khoảng cách Euclide: 16.95


In [85]:
# Tính giá trị trung bình của ba ma trận
arrnull = np.array([0,0,0])
average_matrix = (arr[0] + arr[5] + arr[8])/3
average_matrix2 = (arr[1]+ arr[3]+ arr[4] + arr[7])/4
average_matrix3 = (arr[2] + arr[6])/2
print("Ma trận trung bình:")
print(average_matrix)
print("Ma trận trung bình:")
print(average_matrix2)
print("Ma trận trung bình:")
print(average_matrix3)

Ma trận trung bình:
[ 11.           5.66666667 216.66666667]
Ma trận trung bình:
[ 10.25   5.5  342.5 ]
Ma trận trung bình:
[ 10.5   6.5 625. ]


In [175]:
# Ví dụ: Tính khoảng cách Euclide giữa hai điểm trong không gian ba chiều
point1 = np.array([11. ,          5.66666667, 216.66666667])
point2 = np.array([10.25 ,  5.5 , 342.5])
point3 = np.array([10.5  , 6.5 ,625.])

arr = np.array([[8, 4, 200], [8, 6, 350], [9, 7, 650], [10, 5, 400], [
    11, 4, 320], [11, 8, 250], [12, 6, 600], [12, 7, 300], [14, 5, 200],[11,6,450]])
for i in arr:
    print(i)

    distance = euclidean_distance(i, point3)
    distance = "{:.2f}".format(distance)
    print("Khoảng cách Euclide:", distance)


[  8   4 200]
Khoảng cách Euclide: 425.01
[  8   6 350]
Khoảng cách Euclide: 275.01
[  9   7 650]
Khoảng cách Euclide: 25.05
[ 10   5 400]
Khoảng cách Euclide: 225.01
[ 11   4 320]
Khoảng cách Euclide: 305.01
[ 11   8 250]
Khoảng cách Euclide: 375.00
[ 12   6 600]
Khoảng cách Euclide: 25.05
[ 12   7 300]
Khoảng cách Euclide: 325.00
[ 14   5 200]
Khoảng cách Euclide: 425.02
[ 11   6 450]
Khoảng cách Euclide: 175.00


In [120]:
def initialize_weights(input_dim, num_neurons):
    weights = np.random.random((num_neurons, input_dim))*100
    return weights

In [121]:
arr2 = np.array([[16,124,19],[6,13,70],[10,22,59], [5,81,92],[21,97,23], [7,94,88] ])

In [122]:
print(arr.shape[1])

3


In [123]:
vector = initialize_weights(arr.shape[1], 3)
print(vector)

[[68.05460087  4.44005401 56.33157417]
 [19.02598644 55.10999301  5.4819446 ]
 [57.55191513 41.94747306 56.63958675]]


In [157]:
17.92+0.8* (350-56.6)

291.32

In [162]:
p1 = [68.1,4.4,56.3]
p2 = [19,55.1,5.5 ]
p3 = [57.6,42,56.6]

for i in arr:
    print(i)
    
    distance = euclidean_distance(i, p3)
    distance = "{:.2f}".format(distance)
    print("Khoảng cách Euclide:", distance)

[  8   4 200]
Khoảng cách Euclide: 156.42
[  8   6 350]
Khoảng cách Euclide: 299.73
[  9   7 650]
Khoảng cách Euclide: 596.41
[ 10   5 400]
Khoảng cách Euclide: 348.65
[ 11   4 320]
Khoảng cách Euclide: 270.18
[ 11   8 250]
Khoảng cách Euclide: 201.82
[ 12   6 600]
Khoảng cách Euclide: 546.50
[ 12   7 300]
Khoảng cách Euclide: 250.10
[ 14   5 200]
Khoảng cách Euclide: 154.38


In [131]:
# 68.1+ 0.8 *(8-68.1)
56.3+0.8*(200-56.3)

171.26

In [163]:
def initialize_weights(input_dim, num_neurons):
    weights = np.random.random((num_neurons, input_dim))
    return weights

# Hàm tìm nơ-ron chiến thắng
def find_winner_neuron(sample, weights):
    distances = np.linalg.norm(weights - sample, axis=1)
    winner_neuron = np.argmin(distances)
    return winner_neuron

# Dữ liệu đầu vào
# data = np.array([[1, 2], [2, 1], [1, 3], [3, 2], [5, 4], [4, 5]])

# Số lượng neuron
num_neurons = 3

# Khởi tạo vector trọng số
input_dim = arr.shape[1]
# weights = initialize_weights(input_dim, num_neurons)
# weights = [[68.1,4.4,56.3], [19,55.1,5.5],[57.6,42,56.6]]
weights = np.array([[19,111,21.5], [6.5,88,90.5],[8.5,18,65]])

# Huấn luyện mạng Kohonen
epochs = 10
learning_rate = 0.4

for epoch in range(epochs):
    for sample in arr:
        # Tìm nơ-ron chiến thắng
        winner_neuron = find_winner_neuron(sample, weights)

        # Cập nhật vector trọng số
        weights[winner_neuron] += learning_rate * (sample - weights[winner_neuron])

# In ra vector trọng số của các nơ-ron
print("Vector trọng số:")
print(weights)


Vector trọng số:
[[ 19.         111.          21.5       ]
 [ 12.27453976   5.86217704 258.23171535]
 [ 10.8747903    6.37458163 618.67403072]]


In [147]:
# Hàm khởi tạo vector trọng số
def initialize_weights(input_dim, num_neurons):
    weights = np.random.random((num_neurons, input_dim))
    return weights

# Hàm tìm nơ-ron chiến thắng
def find_winner_neuron(sample, weights):
    distances = np.linalg.norm(weights - sample, axis=1)
    winner_neuron = np.argmin(distances)
    return winner_neuron

# Dữ liệu đầu vào
data = arr

# Số lượng neuron
num_neurons = 3

# Kích thước lưới Kohonen (chọn sao cho lớn hơn số lượng neuron)
grid_size = (2, 2)

# Khởi tạo vector trọng số
input_dim = data.shape[1]
weights = np.array([[19,111,21.5], [6.5,88,90.5],[8.5,18,65]])

# Huấn luyện mạng Kohonen
epochs = 10
learning_rate = 0.8
sigma = grid_size[0] / 2  # Độ rộng của vùng lân cận

for epoch in range(epochs):
    for sample in data:
        # Tìm nơ-ron chiến thắng
        winner_neuron = find_winner_neuron(sample, weights)

        # Tính toán khoảng cách từ nơ-ron chiến thắng đến các nơ-ron khác
        distances = np.linalg.norm(np.indices(grid_size).T.reshape(-1, 2) - np.unravel_index(winner_neuron, grid_size), axis=1)

        # Tính toán hệ số ảnh hưởng (influence) của mỗi nơ-ron
        influence = np.exp(-(distances ** 2) / (2 * sigma ** 2))

        # Cập nhật vector trọng số của nơ-ron chiến thắng và các nơ-ron lân cận
        weights += learning_rate * influence[:, np.newaxis] * (sample - weights)

    # Giảm giá trị sigma sau mỗi epoch
    sigma *= 0.9

# In ra vector trọng số của các nơ-ron
print("Vector trọng số:")
print(weights)

ValueError: operands could not be broadcast together with shapes (4,1) (3,3) 

In [182]:
# arr = np.array([[8, 4, 200], [8, 6, 350], [9, 7, 650], [10, 5, 400], [
#     11, 4, 320], [11, 8, 250], [12, 6, 600], [12, 7, 300], [14, 5, 200]])

arr3 = np.array([[1, 0, 1, 1, 1], [1, 0, 1, 0, 1], [
    0, 0, 1, 1, 1], [1, 0, 0, 1, 0], [0, 1, 0, 1, 0], [0, 1, 0, 0, 1], [0, 0, 0, 0, 0], [1, 1, 1, 0, 1], [0, 1, 0, 1, 0],[1,0,1,0,0]])
p1 = [1, 0, 1, 1, 1]
p2 = [1, 0, 1, 0, 1]
p3 = [0.29, 0.57, 0.14, 0.57, 0.43]
for i in arr3:
    print(i)

    distance = euclidean_distance(i, p3)
    distance = "{:.2f}".format(distance)
    print("Khoảng cách Euclide:", distance)


[1 0 1 1 1]
Khoảng cách Euclide: 1.44
[1 0 1 0 1]
Khoảng cách Euclide: 1.49
[0 0 1 1 1]
Khoảng cách Euclide: 1.29
[1 0 0 1 0]
Khoảng cách Euclide: 1.10
[0 1 0 1 0]
Khoảng cách Euclide: 0.81
[0 1 0 0 1]
Khoảng cách Euclide: 0.97
[0 0 0 0 0]
Khoảng cách Euclide: 0.97
[1 1 1 0 1]
Khoảng cách Euclide: 1.44
[0 1 0 1 0]
Khoảng cách Euclide: 0.81
[1 0 1 0 0]
Khoảng cách Euclide: 1.44


In [169]:
# Tính giá trị trung bình của ba ma trận
# arrnull = np.array([0,0,0])
average_matrix = (arr3[0] + arr3[2])/2
average_matrix2 = (arr3[1]+  arr3[7])/2
average_matrix3 = (arr3[3] + arr3[4] + arr3[5] + arr3[6] + arr3[8])/5
print("Ma trận trung bình:")
print(average_matrix)
print("Ma trận trung bình:")
print(average_matrix2)
print("Ma trận trung bình:")
print(average_matrix3)

Ma trận trung bình:
[0.5 0.  1.  1.  1. ]
Ma trận trung bình:
[1.  0.5 1.  0.  1. ]
Ma trận trung bình:
[0.2 0.6 0.  0.6 0.2]


In [173]:
arr3 = np.array([[1, 0, 1, 1, 1], [1, 0, 1, 0, 1], [
    0, 0, 1, 1, 1], [1, 0, 0, 1, 0], [0, 1, 0, 1, 0], [0, 1, 0, 0, 1], [0, 0, 0, 0, 0], [1, 1, 1, 0, 1], [0, 1, 0, 1, 0]])
p1 = [0.5, 0, 1, 1, 1]
p2 = [1, 0.5, 1, 0, 1]
p3 = [0.2, 0.6, 0, 0.6, 0.2]
for i in arr3:
    print(i)

    distance = euclidean_distance(i, p2)
    distance = "{:.2f}".format(distance)
    print("Khoảng cách Euclide:", distance)

[1 0 1 1 1]
Khoảng cách Euclide: 1.12
[1 0 1 0 1]
Khoảng cách Euclide: 0.50
[0 0 1 1 1]
Khoảng cách Euclide: 1.50
[1 0 0 1 0]
Khoảng cách Euclide: 1.80
[0 1 0 1 0]
Khoảng cách Euclide: 2.06
[0 1 0 0 1]
Khoảng cách Euclide: 1.50
[0 0 0 0 0]
Khoảng cách Euclide: 1.80
[1 1 1 0 1]
Khoảng cách Euclide: 0.50
[0 1 0 1 0]
Khoảng cách Euclide: 2.06


In [6]:
# Ví dụ: Tính khoảng cách Euclide giữa hai điểm trong không gian ba chiều
point1 = np.array([2,10])
point2 = np.array([2,5])
point3 = np.array([5.17,4.6])

arr = np.array([[2,10], [2,5], [8,4], [5,8], [7,5], [6,4], [1,2], [4,9]])
for i in arr:
    print(i)

    distance = euclidean_distance(i, point3)
    distance = "{:.2f}".format(distance)
    print("Khoảng cách Euclide:", distance)

[ 2 10]
Khoảng cách Euclide: 6.26
[2 5]
Khoảng cách Euclide: 3.20
[8 4]
Khoảng cách Euclide: 2.89
[5 8]
Khoảng cách Euclide: 3.40
[7 5]
Khoảng cách Euclide: 1.87
[6 4]
Khoảng cách Euclide: 1.02
[1 2]
Khoảng cách Euclide: 4.91
[4 9]
Khoảng cách Euclide: 4.55


In [ ]:
point1 = np.array([2,10])
point2 = np.array([2,5])
point3 = np.array([5.17,4.6])

arr = np.array([[2,10], [2,5], [8,4], [5,8], [7,5], [6,4], [1,2], [4,9]])
for i in arr:
    print(i)

    distance = euclidean_distance(i, point1)
    distance = "{:.2f}".format(distance)
    print("Khoảng cách Euclide:", distance)

In [19]:
def avg2(x1,y1, x2, y2):
    print((x1+x2)/2)
    print((y1+y2)/2)

In [20]:
def avg3(x1,y1, x2, y2,x3,y3):
    print((x1+x2+x3)/3)
    print((y1+y2+y3)/3)

In [21]:
def avg4(x1,y1, x2, y2,x3,y3,x4,y4):
    print((x1+x2 +x3+x4)/4)
    print((y1+y2+y3+y4)/4)

In [24]:
avg4(8,4,5,8,7,5,6,4)
# avg2(2,5,1,2)

6.5
5.25


In [9]:
point1 = np.array([3, 9.5])
point2 = np.array([1.5,3.5])
point3 = np.array([6.5,5.25])

arr = np.array([[2,10], [2,5], [8,4], [5,8], [7,5], [6,4], [1,2], [4,9]])
for i in arr:
    print(i)

    distance = euclidean_distance(i, point3)
    distance = "{:.2f}".format(distance)
    print("Khoảng cách Euclide:", distance)

[ 2 10]
Khoảng cách Euclide: 6.54
[2 5]
Khoảng cách Euclide: 4.51
[8 4]
Khoảng cách Euclide: 1.95
[5 8]
Khoảng cách Euclide: 3.13
[7 5]
Khoảng cách Euclide: 0.56
[6 4]
Khoảng cách Euclide: 1.35
[1 2]
Khoảng cách Euclide: 6.39
[4 9]
Khoảng cách Euclide: 4.51


In [31]:
avg3(8,4,7,5,6,4)

7.0
4.333333333333333


In [35]:
point1 = np.array([3.66 ,9])
point2 = np.array([1.5,3.5])
point3 = np.array([7,4.33])

arr = np.array([[2,10], [2,5], [8,4], [5,8], [7,5], [6,4], [1,2], [4,9]])
for i in arr:
    print(i)

    distance = euclidean_distance(i, point3)
    distance = "{:.2f}".format(distance)
    print("Khoảng cách Euclide:", distance)

[ 2 10]
Khoảng cách Euclide: 7.56
[2 5]
Khoảng cách Euclide: 5.04
[8 4]
Khoảng cách Euclide: 1.05
[5 8]
Khoảng cách Euclide: 4.18
[7 5]
Khoảng cách Euclide: 0.67
[6 4]
Khoảng cách Euclide: 1.05
[1 2]
Khoảng cách Euclide: 6.44
[4 9]
Khoảng cách Euclide: 5.55


In [6]:
point1 = np.array([2 ,10])
point2 = np.array([2, 5])
point3 = np.array([5.17, 5.33])

arr = np.array([[2,10], [2,5], [8,4], [5,8], [7,5], [6,4], [1,2], [4,9]])
for i in arr:
    print(i)

    distance = euclidean_distance(i, point3)
    distance = "{:.2f}".format(distance)
    print("Khoảng cách Euclide:", distance)

[ 2 10]
Khoảng cách Euclide: 5.64
[2 5]
Khoảng cách Euclide: 3.19
[8 4]
Khoảng cách Euclide: 3.13
[5 8]
Khoảng cách Euclide: 2.68
[7 5]
Khoảng cách Euclide: 1.86
[6 4]
Khoảng cách Euclide: 1.57
[1 2]
Khoảng cách Euclide: 5.34
[4 9]
Khoảng cách Euclide: 3.85
